version: '3.7'

services:

  frontend:
    container_name: frontbluenove
    build: .
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 4000:3000
    stdin_open: true
    command: npm start
    environment:
      - REACT_APP_DOCKERIZED=true
  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    #ports:
    #  - 7000:5000
